config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'listings#index'

  get '/my_listings' => 'listings#my_listings'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, only: [:show, :edit, :update, :destroy]

  resources :listings do
    resources :bookings
  end

  resources :bookings

  resources :bookings do 
    resources :payments, only: [:new, :create]
  end  

  get "/search" => "listings#search"

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  mount_uploaders  :avatars, AvatarUploader
	belongs_to :user
	has_many :listing_tags
	has_many :tags, :through => :listing_tags
	has_many :bookings
	has_many :available_dates
  searchkick
  
  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [
      :search_query,
      :sorted_by,
      :with_country_id,
      :with_tag_ids
    ]
  )

scope :search_query, lambda { |query|
  return nil  if query.blank?

  terms = query.downcase.split(/\s+/)

  terms = terms.map { |e|
    (e.gsub('*', '%') + '%').gsub(/%+/, '%')
  }

  num_or_conds = 2
  where(
    terms.map { |term|
      "(LOWER(listings.title) LIKE ? OR LOWER(listings.address) LIKE ?)"
    }.join(' AND '),
    *terms.map { |e| [e] * num_or_conds }.flatten
  )
}

scope :sorted_by, lambda { |sort_option|
  direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
  case sort_option.to_s
  when /^price/
    order("(listings.price) #{ direction }")
  when /^created_at_/
    order("listings.created_at #{ direction }")
  when /^title_/
         # Simple sort on the name colums
    order("LOWER(listings.title) #{ direction }")
  when /^country_code_/
        # This sorts by a student's country name, so we need to include
        # the country. We can't use JOIN since not all students might have
         # a country.
    order("LOWER(listings.country_code) #{ direction }")

  else
    raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
  end
}

scope :with_country_id, lambda { |country_ids|
  where(country_code: country_ids)
}
 
scope :with_tag_ids, lambda { |tag_ids|
  joins(:tags).where(tags: {id: tag_ids})
}


def self.options_for_sorted_by
  [
    ['Title (a-z)', 'title_asc'],
    ['Creation Date (newest first)', 'created_at_desc'],
    ['Creation Date (oldest first)', 'created_at_asc'],
    ['Country (a-z)', 'country_code_asc'],
    ['Price (high-low)', 'price_desc'],
    ['Price (low-high)', 'price_asc']

    ]
end

def self.countries_with_listings
  arr = ISO3166::Country.all.map {|c| [c.name, c.alpha2]}
  arr = arr.delete_if{|c| Listing.find_by(country_code: c[1]).nil? }
  return arr
end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :find_listing, only: [:show, :edit, :update, :destroy]
	before_action :require_login,  only: [:new, :create, :update, :destroy, :my_listings]

	def index
  		@filterrific = initialize_filterrific(
    	Listing,
    	params[:filterrific],
    	select_options: {
    		sorted_by: Listing.options_for_sorted_by,
    		with_country_id: Listing.countries_with_listings,
    		with_tag_ids: Tag.options_for_select
    	}
	  	) or return
	  	@listings = @filterrific.find

	  	respond_to do |format|
	    	format.html
	    	format.js
  		end
	end

	def search
		@results = Listing.search(params[:search_result])
	end	

	def new
		@listing = Listing.new
	end

	def create
		@listing = current_user.listings.create(listing_params)
		@listing.country_name = country_name
		@listing.save
		respond_to do |format|
			if @listing.save
	        	format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
	      	else
	        	format.html { render :new }
	      	end
	    end
	end
	
	def edit

	end	

	def show
	end

	def update
		respond_to do |format|
      		if @listing.update(listing_params)
        		format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
      		else
        		format.html { render :edit }
      		end
    	end
	end

	def destroy
		@listing.destroy
    	respond_to do |format|
      		format.html { redirect_to listings_url, notice: 'listing was successfully destroyed.' }
    	end
	end

	private

	def my_listings
		@listings = current_user.listings
	end
		

	def listing_params
        params.require(:listing).permit(:title, :address, :price, :country_code, :remove_avatars, tag_ids: [], avatars: [])
    end


	def find_listing
        @listing = Listing.find(params[:id])
    end

    def country_name
    	country_name = ISO3166::Country[params[:listing][:country_code]].name
    end

    def require_login
		unless signed_in?
			flash[:alert] = "You must be logged in to access this section"
			redirect_to '/sign_in'
		end
	end

end

  

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_filterrific_form.html.erb
    <%= form_for_filterrific @filterrific do |f| %>
     	<div class="col-sm-3">
	         Search
	         <%= f.text_field(
	           :search_query,
	           class: 'filterrific-periodically-observed', class: "form-control" 
	         ) %>
      </div>
      <div class="col-sm-3">    
	         Country
	         <%= f.select(
	           :with_country_id,
	           @filterrific.select_options[:with_country_id],
	           { include_blank: '- Any -' }, class: "form-control"
	         ) %>
      </div>
      <div class="col-sm-3">     
         	Sorted by
         	<%= f.select(:sorted_by, @filterrific.select_options[:sorted_by], 
             { include_blank: '- Any -' }, class: "form-control"            
          ) %>
      </div>
      <div class="col-sm-3">    
         	Tagged With:
         	<%= f.select(:with_tag_ids, @filterrific.select_options[:with_tag_ids],
            { include_blank: '- Any -'}, class: "form-control"
          ) %>
       	</div>
       	<div class="col-sm-12">
         <%= link_to(
           'Reset filters',
           reset_filterrific_url,
         ) %>
       </div>
       <%# add an automated spinner to your form when the list is refreshed %>
       <%= render_filterrific_spinner %>
     <% end %>
    <hr>

app/views/listings/_form.html.erb
<div class="row"> 
  <div class="col-md-3">
  <%= form_for(@listing) do |form| %>
    <%= form.label :Title %>
    <%= form.text_field :title, class: "form-control"%>
  </div>
</div>

<div class="row"> 
  <div class="col-md-3">
    <%= form.label :Address %>
    <%= form.text_field :address, class: "form-control"%>
  </div>
</div>  

<div class="row"> 
  <div class="col-md-3">
    <%= form.label :Price %>
    <%= form.text_field :price, class: "form-control"%>
  </div>
</div>

<div class="row"> 
  <div class="col-md-3">
    <%= form.label :country_code %>
    <%= form.country_select :country_code, {selected: "SG"}, class: "form-control" %>
  </div>
</div>
<br>
<div class="row"> 
  <div class="col-md-9">    
    <%= form.label :tag %>
    <%= form.collection_check_boxes :tag_ids, Tag.all, :id, :name, :item_wrapper_class => 'block' , class: "form-control"%>
  </div>
</div>    

<div class="row"> 
  <div class="col-md-3">
    <%= form.label :Upload_pictures %>
    <%= form.file_field :avatars, multiple: true %>
  </div>
</div>  
<p>
    <label>
      <%= form.check_box :remove_avatars %>
      Remove avatars
    </label>
</p>

  <%= form.submit %>
<%end%>

app/views/listings/_list.html.erb
<div id="filterrific_results">
  <div class="container">
    <div class="row">
    <%listings.each do |listing|%>
      <div class="col-sm-4">
        <div class="panel panel-primary">
          <div class="panel-heading"><%=listing.title%></div>
          <div class="panel-body"><img src="<%=listing.avatars_urls.first%>" class="img-responsive" style="width:325px; height:200px;" alt="Image"></div>
          <div class="panel-footer">
          <%= link_to 'Book Now', new_listing_booking_path(listing) %> 
          <p class="pull-right"><%= link_to 'More Info', listing %></p>
          </div>
        </div>
      </div>
      <%end%>
    </div>
  </div>
</div>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<div class="container">
	<% if @errors %>
	  <%= @errors %>
	<% end %> 
	<%= render "listings/filterrific_form"%>
	<%= render( partial: 'listings/list', locals: { listings: @listings } ) %>

	<%= link_to 'Create a listing', new_listing_path %> 
</div>

app/views/listings/index.js.erb
<% js = escape_javascript(
  render(partial: 'listings/list', locals: { listings: @listings })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/listings/my_listings.html.erb
<div class="container" style="border: 1px solid gray;">
<% if @listings %>
	<h3> My Listings </h3>
	<table class="table">
		<tr>
			<th>Title</th>
			<th>Address</th>
			<th>Price</th>
			<th>Country</th>
			<th>More Info</th>
		</tr>
		<% @listings.each do |listing|%>
		<tr>
			<td><%=listing.title%></td>
			<td><%=listing.address%></td>
			<td><%=listing.price%></td>
			<td><%=listing.country_name%></td>
			<td><%= link_to 'Show', listing_path(listing) %></td>
		</tr>
		<%end%>
	</table>	
<%end%>
</div>

app/views/listings/new.html.erb
<div class="container">
	<h1>New Listing</h1>

	<%= render 'form' %>

	<%= link_to 'Back', listings_path %>
</div>

app/views/listings/search.html.erb
<%if @results %>
<div class="container">
  <div class="row">
  <%@results.each do |result|%>
    <div class="col-sm-4">
      <div class="panel panel-primary">
        <div class="panel-heading"><%=result.title%></div>
        <div class="panel-body"><img src="<%=result.avatars_urls.first%>" class="img-responsive" style="width:325px; height:200px;" alt="Image"></div>
        <div class="panel-footer">
        <%= link_to 'Book Now', new_listing_booking_path(result) %> 
        <p class="pull-right"><%= link_to 'More Info', result %></p>
        </div>
      </div>
    </div>
    <%end%>
  </div>
</div>
</div>
<%end%>
<%= link_to 'Back to Listings', listings_url %>

app/views/listings/show.html.erb
<%if @listing %>
	<div class="container" style=" background-color: #ddd;">
		<div class="row">
			<div class="col-md-2">
				<h4>Title:</h4>
			</div>
			<div class="col-md-4" style="top: 10px; bottom: 10px;">
				<p><%=@listing.title%></p>
			</div>
		</div>	
		<div class="row">
			<div class="col-md-2">
				<h4>Address:</h4>
			</div>
			<div class="col-md-4" style="top: 10px; bottom: 10px;">
				<%=@listing.address%>
			</div>				
		</div>
		<div class="row">
			<div class="col-md-2">
				<h4>Price:</h4>
			</div>
			<div class="col-md-4" style="top: 10px; bottom: 10px;">
				<%=@listing.price%>
			</div>				
		</div>
		<div class="row">
			<div class="col-md-2">
				<h4>Tag:</h4>
			</div>
			<div class="col-md-4" style="top: 10px; bottom: 10px;">
				<% @listing.tags.each do |tag|%>
					<%= tag.name + ',' %>
				<% end %>	
			</div>				
		</div>
		<div class="row">
			<div class="col-md-2">
				<h4>Country:</h4>
			</div>
			<div class="col-md-4" style="top: 10px; bottom: 10px;">
				<%=ISO3166::Country[@listing.country_code].name
				%>
			</div>				
		</div>
		<div class="row">
			<div class="col-md-2">
				<% if signed_in? and current_user.id == @listing.user_id %>
					<%= link_to "Edit", edit_listing_path(@listing) %>
					<%= link_to 'Destroy', @listing, method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %>
			</div>
		</div>	
		<div class="row">
			<div class="col-md-2">	
				<%= link_to 'Book this Place', new_listing_booking_path(@listing) %>
			</div>	
		</div>		
		<div class ="row">
			<div class="col-md-2">
				<%= link_to 'Back', listings_path %><br>
			</div>
		</div>
	</div>	
<%end%>
<br>
<br>
<div class="container">
	<div class="row">
		<%@listing.avatars.each do |avatar|%>
	  		<div class="col-sm-4">
	    		<div class="panel panel-primary">
	      			<div class="panel-body"><img src="<%=avatar%>" class="img-responsive" style="width:325px; height:200px;" alt="Image"></div>
	    		</div>
	  		</div>
	  	<%end%>
	</div>
</div>