config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'listings#index'

  get '/my_listings' => 'listings#my_listings'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, only: [:show, :edit, :update, :destroy]

  resources :listings do
    resources :bookings
  end

  resources :bookings

  resources :bookings do 
    resources :payments, only: [:new, :create]
  end  

  get "/search" => "listings#search"

end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :user
	belongs_to :listing
    has_many :payments
    validate :check_overlapping_bookings

    def check_overlapping_bookings
        unavailable_dates = listing.available_dates.pluck(:booked_date)
        dates_to_book = (start_date .. end_date).to_a
        non_overlapping_dates = dates_to_book - unavailable_dates
        if dates_to_book == non_overlapping_dates
        	return
        else	
        	errors.add(:overlapping_dates, "dates are already taken")
        end
    end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	before_action :require_login,  only: [:index, :create, :new, :show, :edit, :destroy]

	def index
		@bookings = current_user.bookings.all
	end	

	def new
		@booking = Booking.new
		set_listing
	end

	def create
    	set_listing
    	@booking = current_user.bookings.new(booking_params)
    	@booking.listing = @listing
		if @booking.save
			#BookingMailer.booking_email(@booking, @listing).deliver_later
			#DeleteBookingJob.perform_in(1.minutes.from_now, @booking)
			DeleteBookingJob.set(wait: 1.minutes).perform_later(@booking)
			MailJob.perform_later(@booking, @listing)
			reserve_dates(@booking.start_date, @booking.end_date, @listing.id)
        	redirect_to new_booking_payment_path(@booking)
      	else
      		@errors = @booking.errors.full_messages
        	redirect_to listings_path
      	end
	end

	def show
		@booking = Booking.find(params[:id])
	end

	def edit
		set_listing
		@booking = Booking.find(params[:id])
	end

	def destroy
		@booking = Booking.find(params[:id])
		@booking.destroy
    	respond_to do |format|
      		format.html { redirect_to listings_url, notice: 'Booking was successfully destroyed.' }
    	end
	end


	private

	def booking_params
        processed_params = params.require(:booking).permit(:start_date, :end_date, :guest, :listing_id)
        processed_params[:start_date] = Date.strptime(processed_params[:start_date], "%m/%d/%Y")
        processed_params[:end_date] = Date.strptime(processed_params[:end_date], "%m/%d/%Y")
        return processed_params
    end

	def set_listing
        @listing = Listing.find(params[:listing_id])
    end

    def reserve_dates(start_date, end_date, listing_id)
    	dates_booked = (start_date..end_date).to_a
    	dates_booked.each do |date|
    		available_date = AvailableDate.new
    		available_date.booked_date = date
    		available_date.available = false
    		available_date.listing_id = listing_id
    		available_date.save
    	end	
    end

    def require_login
		unless signed_in?
			flash[:alert] = "You must be logged in to access this section"
			redirect_to '/sign_in'
		end
	end


end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
  <div class="row">
    <div class="col-md-6">
      <%= form_for [@listing, @booking] do |f| %>
        <div class="input-daterange input-group" id="datepicker">
          <%= f.text_field :start_date, class: "input-sm form-control", placeholder: "From Date" %>
          <span class="input-group-addon">to</span>
          <%= f.text_field :end_date, class: "input-sm form-control", placeholder: "To Date"%>
        </div>
        <br>
        <div>
          <%= f.label :number_of_guest %>
        	<%= f.number_field :guest%>
      	</div>
        <br>
        <div>
         <%= f.submit "Submit"%>
         </div>
      <% end %>
    </div>
  </div>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form' %>

<%= link_to 'Show', listing_booking_path(@listing, @booking) %> 
<%= link_to 'Back', listing_bookings_path %>

app/views/bookings/index.html.erb
<div class="container" style="border: 1px solid gray;">
<% if @bookings %>
	<h3> My bookings </h3>
	<table class="table">
		<tr>
			<th>Start Date</th>
			<th>End Date</th>
			<th>Number of Guests</th>
			<th>Booked At</th>
			<th>Show</th>
		</tr>
		<% @bookings.each do |booking|%>
		<tr>
			<td><%=booking.start_date%></td>
			<td><%=booking.end_date%></td>
			<td><%=booking.guest%></td>
			<td><%=Listing.find(booking.listing_id).title%></td>
			<td><%= link_to 'Show', listing_path(booking.listing_id) %></td>
		</tr>
		<%end%>
	</table>	
<%end%>
</div>

app/views/bookings/new.html.erb
<div class="container" style="border: 1px solid gray;">
<h1>Booking at <%=Listing.find(params[:listing_id]).title%></h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>
</div>

app/views/bookings/show.html.erb
<div class="container" style="color: #999999;">
<h3>Congratulations! Your transaction has been successfull!</h3>
<h4> Your booking has been made at <b><%= @booking.listing.title %></b> from <%=@booking.start_date%>
to <%= @booking.end_date %> for <%=@booking.guest%> guest(s).</h4>

<h4>Click here for more info </h4>
<%= link_to 'More info', listing_path(@booking.listing.id) %>
</div>