config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'listings#index'

  get '/my_listings' => 'listings#my_listings'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, only: [:show, :edit, :update, :destroy]

  resources :listings do
    resources :bookings
  end

  resources :bookings

  resources :bookings do 
    resources :payments, only: [:new, :create]
  end  

  get "/search" => "listings#search"

end

app/models/user.rb
class User < ActiveRecord::Base

  include Clearance::User
  mount_uploader :avatar, AvatarUploader
   has_many :listings
   has_many :bookings
   has_many :payments

  has_many :authentications, :dependent => :destroy

  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.password = "PLACEHOLDER"
      u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_login,  only: [:index, :update, :show, :edit]

	def index
		@users = User.all
	end
	
	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def create
	end	

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		redirect_to @user
	end

	private

	def user_params
        params.require(:user).permit(:email, :password, :avatar, :remove_avatar)
    end

    def require_login
		unless signed_in?
			flash[:alert] = "You must be logged in to access this section"
			redirect_to '/sign_in'
		end
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for :user, url: users_path do |form| %>

<div class="text-field">
   <%= form.label :email %>
   <%= form.text_field :email, type: 'email', class: 'form-control' %>
</div>
 
<div class="password-field">
   <%= form.label :password %>
   <%= form.password_field :password , class: 'form-control'%>
</div>

  <%= form.submit %>

<%end%>

app/views/users/edit.html.erb
<%= form_for @user do |form| %>

<div class="text-field">
   <%= form.label :email %>
   <%= form.text_field :email, type: 'email' %>
</div>
 
<div class="password-field">
   <%= form.label :password %>
   <%= form.password_field :password %>
</div>

<div> 
   <%= form.label :upload_avatar %>
   <%= form.file_field :avatar, multiple: false %>
</div>
<p>
    <label>
      <%= form.check_box :remove_avatar %>
      Remove avatar
    </label>
</p>
   <%= form.submit %>

<%end%>

app/views/users/index.html.erb
<h1>Welcome</h1>
<% @users.each do |user| %>
	<table>
		<td><%=user.email%></td>
		<td><%= link_to 'Show', user %></td>
		<%if signed_in? and current_user.id == user.id %>
			<td><%= link_to "Edit", edit_user_path(user) %></td>
		<%end%>
	</table>
<%end%>		
<%= link_to 'Go to listings', listings_path %>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div id="clearance" class="sign-up">
         <h2><%= t(".title") %></h2>       
         <%= form_for @user do |form| %>
           <%= render partial: '/users/form', object: form %>       
           <div class="submit-field">
             <%= form.submit %>
           </div>       
           <div class="other-links">
             <%= link_to t(".sign_in"), sign_in_path %>
           </div>
         <% end %>
      </div>
    </div>
  </div>    
</div>

app/views/users/show.html.erb
<%=@user.email%>
<% if current_user.id == @user.id %>
	<%= link_to 'Edit', edit_user_path(@user) %> 
<% end %>	
<% if @user.avatar %>
	<%= image_tag(@user.avatar.thumb) %>
<% end %>	