config/routes.rb
Rails.application.routes.draw do
  get 'payments/new'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'listings#index'

  get '/my_listings' => 'listings#my_listings'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, only: [:show, :edit, :update, :destroy]

  resources :listings do
    resources :bookings
  end

  resources :bookings

  resources :bookings do 
    resources :payments, only: [:new, :create]
  end  

  get "/search" => "listings#search"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= include_gon %>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'application' %>
  <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
  <%= csrf_meta_tag %>
</head>
<body>
<nav class="navbar navbar-default" >
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">PairBnB</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%if !signed_in? %>
          <li class="btn" style="padding-top: 12px;"><button data-toggle="modal" data-target="#LoginModal"> Login <span class="sr-only">(current)</span></button></li> 
        <%end%>  
      </ul>

      <form class="navbar-form navbar-left" action="/search">
        <div class="form-group">
          <input type="text" name="search_result" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="listings/new">Become a Host</a></li>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle"  value="<%=current_user.email%>" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=current_user.email%> 
             <span class="caret"></span></a>
        <%end%>    
          <ul class="dropdown-menu">
            <% if signed_in? and current_user %>
              <li><%= link_to "My Profile", user_path(current_user) %></li>
              <% if current_user.listings %>
                <li><a href="/my_listings">My Listings</a></li> 
              <%end%>
              <% if current_user.bookings %>                
                <li><a href="/bookings">My bookings</a></li> 
              <%end%>  
            <%else%>
              <li><%= link_to t(".sign_in"), sign_in_path %></li>
            <% end %>  
            <% if signed_in? and current_user %>
              <li role="separator" class="divider"></li>
              <li><%= link_to t(".sign_out"), sign_out_path, method: :delete %></li>
            <%end%>  
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  	<%= yield %>
    
<div class="modal fade" id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" width="900px">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Login Page</h4>
      </div>
      <%= form_for :session, url: session_path do |form| %>
        <div class="row">
          <div class="col-md-3"></div>
          <div class="col-md-6">
            <div class="text-field">
              <%= form.label :email %>
              <%= form.text_field :email, type: 'email', class: 'form-control' %>
            </div>
          </div>
        </div>   
        <div class="row">
          <div class="col-md-3"></div>
          <div class="col-md-6"> 
            <div class="password-field">
              <%= form.label :password %>
              <%= form.password_field :password, class: 'form-control' %>
            </div>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-md-3"></div>
          <div class="col-md-3">    
            <div class="submit-field">
              <%= form.submit %>
            </div>
          </div> 
        </div>  
        <div class="row">
          <div class="col-md-3"></div>
          <div class="col-md-6">
            <div class="other-links">
              <% if Clearance.configuration.allow_sign_up? %>
                <%= link_to t(".sign_up"), sign_up_path %>
              <% end %>
              <%= link_to t(".forgot_password"), new_password_path %>
            </div>  
          </div>
        </div>              
        <% end %>
        <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <%= link_to "Sign in with facebook", "/auth/facebook" %>
        </div>  
    </div>
  </div>
</div>
</body>
</html>